trigger: none

stages:
  - stage: Welcome
    displayName: "Welcome"
    jobs:
      - deployment: PrintHelloDeployment
        displayName: "Say Hello Job"
        environment: "1st Demo Environment"
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Hello Environments!"
                  displayName: "Echo Hello Environments"
